version: "2.2"
services:

  mio_webserver:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./php_rest_demo-main:/var/www/html/rest
  db_name:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ciccio
  mio_phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
